# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem 'base32', '~> 0.3.4'
gem 'ed25519', '~> 1.3'
gem 'digest', '~> 3.1'
gem 'sha3', '~> 1.0', '>= 1.0.4'
gem 'test-unit', '~> 3.2', '>= 3.2.9'
gem 'activerecord', '~> 7.0', '>= 7.0.4'
